### ISSUE TITLE
SlackRequest verify raises `undefined method `bytesize' for nil` if missing signature

### ISSUE THREAD

**Issue by wesleyjellis** [slack-ruby/slack-ruby-client#563]
Minor regression after https://github.com/slack-ruby/slack-ruby-client/pull/553

If you instantiate a request without a signature, instead of getting `InvalidSignature` when calling `verify` you get `undefined method`

```
=> #<NoMethodError: undefined method `bytesize' for nil>
[2] pry(#<Integrations::Slack::WebhooksController>)> error.backtrace
=> ["/Users/wesley/.asdf/installs/ruby/3.3.7/lib/ruby/gems/3.3.0/gems/slack-ruby-client-2.6.0/lib/slack/utils/security.rb:38:in `secure_compare'",
 "/Users/wesley/.asdf/installs/ruby/3.3.7/lib/ruby/gems/3.3.0/gems/slack-ruby-client-2.6.0/lib/slack/events/request.rb:63:in `valid?'",
...
```
